# Site settings
title: Face to fesses
baseurl: ""
baseurl_image: "/img"
url: "http://facetofesse.fr"

# SEO & head
twitter_username: "@FaceToFesses"
twitter_creator: "@quentin_neyraud"
meta_description: "Face to fesses est un projet ayant pour but de dissiper les craintes des adolescents à l'approche de leur première fois."
share_image: "/share-image.png"
favicon: "/favicon.png"

# Build settings
markdown: kramdown
source: src
destination: public

assets_path: '/build/'
