# Site settings
title: Jekyll starter
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
baseurl_image: "/img/"
url: "http://jekyll-starter.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
source: src
destination: public

assets_path: '/build/'
