# Site settings
title: Face to fesses
baseurl: ""
baseurl_image: "/img"
url: "http://facetofesses.fr"

# SEO & head
twitter_username: "@FaceToFesses"
twitter_creator: "@quentin_neyraud"
meta_description: "Face to Fesse accompagne les adolescents dans la découverte de leur sexualité grâce à un parcours interactif qui démystifie la première fois !"
share_image: "/share-image.png"
favicon: "/favicon.ico"

# Build settings
markdown: kramdown
source: src
destination: public

assets_path: '/build/'
